# Zadanie 1. Kalkulator trajektorii lotu pocisku

Zaimportuj z moduł `math` następujące funkcje:
* `sin` (nazwij `sinus`) - zwraca wartość funkcji sinus dla kąta podanego w radianach;
* `cos` (nazwij `cosinus`) - zwraca wartość funkcji cosinus dla kąta podanego w radianach;
* `radians` (nazwij `deg_to_rad`) - konwertuje wartość ze stopni na radiany;
* `pow` (nazwij `potega`) - oblicza potęgę ustalonego stopnia.

Program pyta użytkownika o dwie wartości:
* $v$ - prędkość wylotowa pocisku (m/s);
* $\theta$ - kąt wyrzutu pocisku (stopnie).

Następnie program oblicza:
* maksymalną wysokość jaką osiągnie pocisk w trakcie lotu: $h_{max}=\frac{v^2\cdot sin^2(\theta_r)}{2g}$
* czas lotu pocisku: $t=\frac{2v\cdot sin(\theta_r)}{g}$
* zasięg pocisku: $\text{range}=\frac{v^2\cdot sin(2\theta_r)}{g}$

gdzie:
* $g$ - przyspieszenie ziemskie: $g=9.81\space m/s^2$
* $\theta_r$ - kąt wyrzutu pocisku wyrażony w radianach: $\theta_r=\text{deg\_to\_rad} (\theta)$

Program wypisuje wynik na ekran z dokładnością do dwóch miejsc po przecinku i ze stosownym opisem.

In [2]:
from math import sin as sinus
from math import cos as cosinus
from math import radians as deg_to_rad
from math import pow as potega

In [3]:
#inputy od usera + przyspieszenie
v= float(input("podaj predkosc wylotowa pocisku (m/s): "))
th= float(input("podaj kąt wyrzutu pocisku: "))
g= 9.81

#wzory do obliczeniowek
max= (potega(v, 2)*potega(sinus(deg_to_rad(th)), 2))/ 2*g
t= (2*v*sinus(deg_to_rad(th)))/ g
range= (potega(v, 2)*sinus(2*deg_to_rad(th)))/ g

#wyniki
print(f"{max:.2f} m")
print(f"{t:.2f} s")
print(f"{range:.2f} m")

podaj predkosc wylotowa pocisku (m/s):  45
podaj kąt wyrzutu pocisku:  50

5828.70 m
7.03 s
203.29 m

# Zadanie 2. Analiza sekwencji genetycznych.

Zaimportuj z modułu `random` następujące funkcje:
* `choice` - losuje jedną wartość z podanego zestawu opcji;
* `random` - losuje wartość z przedziału $0-1$.

Zaimplementuj następujące funkcje:
* `generuj_dna(d: int) -> str`: funkcja przyjmuje jako parametr długość sekwencji do wygenerowania i zwraca sekwencję DNA wygenerowaną w sposób losowy opierając się na słowniku znanych nukleotydów;
* `mutuj_dna(sekwencja: str, pr_mut: float) -> str`: funkcja przyjmuje dwa parametry: sekwencja DNA i prawdopodobieństwo mutacji, dokonuje losowych zmian w oryginalnej sekwencji i zwraca sekwencję zmutowaną;
* `podobienstwo(sekwencja1, sekwencja2) -> float`: funkcja jako parametry przyjmuje dwie sekwencje i następnie oblicza liczbę różnic między sekwencjami. Następnie oblicza procentową zawartość różnic w stosunku do długości pierwszej sekwencji i zwraca podobieństwo wyrażone jako $\text{podobieństwo}=1-\frac{\text{liczba różnic}}{\text{długść sekwencji}}$.

Program generuje sekwencję ustalonej długości. Następnie dokonuje mutacji tej sekwencji i oblicza podobieństwo sekwencji oryginalnej do zmutowanej. Na koniec wypisuje na ekran podobieństwo obu sekwencji wyrażone jako wartość procentowa w zaokrągleniu do 2 miejsc po przecinku. Dodatkowo, jeżeli podobieństwo obu sekwencji jest większe niż $97\%$ to program wypisuje na ekran komunikat, że obie sekwencje pochodzą od organizmów tego samego gatunku.

In [5]:
from random import choice, random

In [6]:
length = int(input("Podaj długość losowej sekwencji DNA: "))

nukleotydy= ['A', 'C', 'G', 'T']
los_nukl= choice(nukleotydy)
seq= " "
for i in range(length):
    seq += choice(nukleotydy)
print(f"Losowa sekwencja DNA: {seq}")

Podaj długość losowej sekwencji DNA:  15

TypeError: 'float' object is not callable

In [ ]:
d= int(input("podaj dlugosc losowej sekwencji: "))

def gen_dna(d: int) -> str:
    nukl= ['A', 'C', 'G', 'T']
    seq = ""
    
    for _ in range(d):
        seq += choice(nukl)
    return seq

seq_los= gen_dna(d)
print(f"Losowa sekwencja DNA: {seq_los}")

#2 mutowanie
def mut_dna(seq: str, pr_mut: float) -> str:
    nukl= ['A', 'C', 'G', 'T']
    mutowane= ""

    for nukld in seq:
        if random()<= pr_mut:
            mutowane += choice(nukl)
        else:
            mutowane += nukld
    return mutowane

mut_seq = mut_dna(seq_los, random())
print(f"Mutowana sekwencja DNA: {mut_seq}")

#3
seq1 = seq_los
seq2 = mut_seq
def podobienstwo(seq1, seq2) -> float:
    roznice= 0

    for i in range(len(seq1)):
        if seq1[i] != seq2[i]:
            roznice += 1

    return 1-roznice/ len(seq1)

pod= podobienstwo(seq1, seq2)
print(f"Podobieństwo między sekwencjami: {pod:.2f}")

if pod >= 0.97:
    print("Sekwencje pochodzą od organizmu tego samego gatunku.")
else:
    print("Sekwencje pochodzą od organizmów różnych gatunków.")

# Zadanie 3. Oczyszczanie metadanych środowiskowych.

Zaimportuj moduł pandas i przypisz mu stosowną nazwę. Wczytaj zestaw danych `data/environmental_metadata.csv`. Jest to zbiór metadanych opisujących próbki pobrane ze środowiska na terenie Polski. Posiada on następujący zestaw cech:
* site: nazwa stanowiska
* season: pora roku, w której pobierana była próba
* depth: głębokość wody z jakiej pobrano próbę, standardowo próbkę pobierano na trzech głębokościach: 20 cm, 50 cm i 80 cm
* molecule: nazwa cząsteczki jaka była izolowana z próbki: DNA lub RNA
* rep_number: numer powtórzenia, każda próba była pobierana 5 razy w 5 różnych miejscach na jednym stanowisku
* latitude: szerokość geograficzna stanowiska
* longitude: długość geograficzna stanowiska
* temperature: temperatura powietrza podczas pobierania próbki
* humidity: wilgotność powietrza podczas pobierania próbki
* particles: średnia liczba cząsteczek stałych w jednym militrze pobranej próbki
* comment: komentarz osoby pobierającej próbę o szczególnych okolicznościach podczas pobierania próbki.

Oczyść dane wykonując następujące kroki:
1. Sprawdź czy zestaw zawiera brakujące dane. Jeżeli tak, użyj metody `.dropna()` aby pozbyć się braków. Zwróć uwagę na to czy należy usunąć wiersze czy kolumny.
2. Sprawdź czy wszystkie zmienne mają taki typ jaki powinny mieć (użyj metody `.info()` na całej tabeli). Jeżeli nie, podmień taką zmienną na przekonwertowaną z użyciem metody `.astype()` na konkretnej kolumnie (serii danych).
3. Przeszukaj zbiór pod kątem niepoprawnych wartości analizując wartości zmiennych merytorycznie, np. szerokość geograficzna obejmuje wartości z przedziału od $-90^o$ do $+90^o$. Wykorzystaj do tego analizę podstawowych statystyk (metoda `.describe()`).
4. Usuń zidentyfikowane niepoprawne wiersze ze zbioru.

Sprawdź ile wierszy i ile kolumn zostało usuniętych ze zbioru. Wynikowy zestaw danych zapisz do pliku `data/environmental_metadata_clean.csv`.

In [69]:
import pandas as pd
envi= pd.read_csv("data/environmental_metadata.csv")

In [71]:
envi.head()

,site,season,depth,molecule,rep_number,latitude,longitude,temperature,humidity,particles,comment
0,stanowisko_1,spring,20.0,DNA,1.0,50.504714,15.996064,15.0,65.0,489.664734,NaN
1,stanowisko_1,spring,20.0,RNA,1.0,50.504714,15.996064,15.0,65.0,520.061491,NaN
2,stanowisko_1,spring,50.0,DNA,1.0,50.504714,15.996064,15.0,65.0,215.970936,NaN
3,stanowisko_1,spring,50.0,RNA,1.0,50.504714,15.996064,15.0,65.0,725.342452,NaN
4,stanowisko_1,spring,80.0,DNA,1.0,50.504714,15.996064,15.0,65.0,823.053115,NaN

In [73]:
envi.info() #11 kolumn 1530 wierszy

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   site         1528 non-null   object
 1   season       1526 non-null   object
 2   depth        1529 non-null   float64
 3   molecule     1529 non-null   object
 4   rep_number   1530 non-null   float64
 5   latitude     1529 non-null   float64
 6   longitude    1528 non-null   float64
 7   temperature  1530 non-null   float64
 8   humidity     1528 non-null   float64
 9   particles    1529 non-null   float64
 10  comment      36 non-null     object
dtypes: float64(7), object(4)
memory usage: 131.6+ KB

In [75]:
envi.isna().sum()

site              2
season            4
depth             1
molecule          1
rep_number        0
latitude          1
longitude         2
temperature       0
humidity          2
particles         1
comment        1494
dtype: int64

In [77]:
envi.describe().T

,count,mean,std,min,25%,50%,75%,max
depth,1529.0,50.000000,24.510923,20.000000,20.000000,50.000000,80.000000,80.000000
rep_number,1530.0,3.000000,1.414676,1.000000,2.000000,3.000000,4.000000,5.000000
latitude,1529.0,51.925616,16.764722,5.003142,50.504714,50.865460,52.314923,516.946116
longitude,1528.0,19.504439,7.328033,1.873976,16.918580,19.694106,21.018274,220.776616
temperature,1530.0,17.847712,12.800566,-73.000000,9.000000,18.000000,25.000000,311.000000
humidity,1528.0,57.556283,25.032751,-7.000000,40.000000,58.000000,75.000000,117.000000
particles,1529.0,503.214748,301.601399,-456.989559,303.683929,509.956062,701.604707,1386.492342

In [79]:
envi= envi.drop(columns=["comment"])
envi.dropna(inplace=True)

In [81]:
envi["rep_number"] = envi["rep_number"].astype(int)

In [ ]:
#ogolem, jesli dane sa z polski to: 1. wilgotnosc nie moze byc powyzej 100% (nie mozliwe, bo inczej woda powinna sie skraplac); 
# 2. leży w granicach ok. 49 do 55 stopni N szerokości geo. i 14 do 24 stopni E dlugosci geo., reszta wypada;
# 3. temp. sa z wiosny, lata, jesieni wiec kazde drastyczne skoki/spadki temp. beda usuniete; 
# 4. particles nigdy nie powinny byc ujemne

In [83]:
envi["depth"].nlargest()

4     80.0
5     80.0
10    80.0
11    80.0
16    80.0
Name: depth, dtype: float64

In [115]:
envi["depth"].value_counts().nunique() #507, 501, 499 wyskakuje przy value counts

depth
20.0    507
80.0    501
50.0    499
Name: count, dtype: int64

In [85]:
#envi["humidity"].value_counts()
envi["humidity"].nlargest(42) # 439-449, 666-677, 348-353, 102-107 do usuniecia
envi["humidity"].nsmallest(12) #834-389, 489-503 usunac trzeba

834   -7.0
835   -7.0
836   -7.0
837   -7.0
838   -7.0
839   -7.0
498   -6.0
499   -6.0
500   -6.0
501   -6.0
502   -6.0
503   -6.0
Name: humidity, dtype: float64

In [117]:
#warunek do usuniecia przedzialow powyzej
usun= envi[(envi["humidity"] >= 0)]

In [89]:
envi["latitude"].nlargest(10) # 1121, 324
envi["latitude"].nsmallest(10) # 932, 597

932     5.003142
597     5.124010
900    50.031419
901    50.031419
902    50.031419
903    50.031419
904    50.031419
905    50.031419
906    50.031419
907    50.031419
Name: latitude, dtype: float64

In [91]:
envi["longitude"].nlargest(10) # 894, 1354
envi["longitude"].nsmallest(10) #125 do usuniecia

125      1.873976
1260    15.356903
1261    15.356903
1262    15.356903
1263    15.356903
1264    15.356903
1265    15.356903
1266    15.356903
1267    15.356903
1268    15.356903
Name: longitude, dtype: float64

In [95]:
envi["season"].value_counts()

season
spring    506
summer    506
autumn    504
Name: count, dtype: int64

In [97]:
envi["temperature"].nlargest(25) # 1034
envi["temperature"].nsmallest(30) # 358 trzeba usunac

358   -73.0
384    -5.0
385    -5.0
386    -5.0
387    -5.0
388    -5.0
389    -5.0
372    -3.0
373    -3.0
374    -3.0
375    -3.0
376    -3.0
377    -3.0
378    -2.0
379    -2.0
380    -2.0
381    -2.0
382    -2.0
383    -2.0
294    -1.0
295    -1.0
296    -1.0
297    -1.0
298    -1.0
299    -1.0
336    -1.0
337    -1.0
338    -1.0
339    -1.0
340    -1.0
Name: temperature, dtype: float64

In [99]:
#envi["particles"].value_counts()
envi["particles"].nlargest() 
envi["particles"].nsmallest(10)

82     -456.989559
754    -373.944203
1250   -349.185907
47     -347.342008
1355   -341.655915
569    -313.051393
442    -309.464172
808    -295.509780
1012   -293.875634
294    -280.338347
Name: particles, dtype: float64

In [101]:
# jest duzo wartosci na minusie
usun= envi[(envi["particles"] >= 0)]

In [103]:
print(envi.loc[968]) #checking if sth more is incorrect in a full picture

site           stanowisko_11
season                autumn
depth                   50.0
molecule                 DNA
rep_number                 2
latitude           50.031419
longitude          22.355054
temperature             16.0
humidity                65.0
particles         -82.787587
Name: 968, dtype: object

In [ ]:
1121, 324, 932, 597, 894, 1354, 125, 1034, 358

In [105]:
usunac= [1121, 324, 932, 597, 894, 1354, 125, 1034, 358]
envi.drop(usunac, inplace=True) #deleting incorrect data

In [107]:
envi.info() # 10 kolumn 31 wierszy

<class 'pandas.core.frame.DataFrame'>
Index: 1507 entries, 0 to 1528
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   site         1507 non-null   object
 1   season       1507 non-null   object
 2   depth        1507 non-null   float64
 3   molecule     1507 non-null   object
 4   rep_number   1507 non-null   int64
 5   latitude     1507 non-null   float64
 6   longitude    1507 non-null   float64
 7   temperature  1507 non-null   float64
 8   humidity     1507 non-null   float64
 9   particles    1507 non-null   float64
dtypes: float64(6), int64(1), object(3)
memory usage: 129.5+ KB

In [65]:
oryginal= pd.read_csv("data/environmental_metadata.csv")

In [67]:
oryginal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   site         1528 non-null   object
 1   season       1526 non-null   object
 2   depth        1529 non-null   float64
 3   molecule     1529 non-null   object
 4   rep_number   1530 non-null   float64
 5   latitude     1529 non-null   float64
 6   longitude    1528 non-null   float64
 7   temperature  1530 non-null   float64
 8   humidity     1528 non-null   float64
 9   particles    1529 non-null   float64
 10  comment      36 non-null     object
dtypes: float64(7), object(4)
memory usage: 131.6+ KB

In [119]:
n= 1530- 1507
m= 11-10
print(f"zostalo usuniete {n} wieszy i {m} kolumn.")

zostalo usuniete 23 wieszy i 1 kolumn.

In [ ]:
envi.to_csv("data/environmental_metadata_clean.csv")

# Zadanie 4. Grupowanie i agregacja danych.

Wczytaj oczyszczony zestaw danych `data/environmental_metadata_clean.csv`. 
1. Zbadaj ile powtórzeń każdej próby pozostało w zbiorze dla każdego stanowiska, w każdym sezonie, z każdej głębokości i dla każdej molekuły. 
2. Oblicz średnią temperaturę i wilgotność jaka panowała w momencie poboru prób na każdym stanowisku w każdej porze roku.
3. Sprawdź ile średnio cząsteczek występowało w próbce na jesień, na głębokości 50 cm na stanowisku trzecim i czwartym.

In [ ]:
cenv= pd.read_csv("data/environmental_metadata_clean.csv")

In [ ]:
rp= cenv.groupby(["site", "season", "depth", "molecule"]).size().reset_index(name= "count")
print(rp)

In [ ]:
cenv.head()

In [ ]:
avg_con= cenv.groupby(["site", "season"])[["temperature", "humidity"]].mean()
print(avg_con)

In [ ]:
filtr = ((cenv["season"].isin(["autumn"])) & (cenv["depth"] == 50) & (cenv["site"].isin(["stanowisko_3", "stanowisko_4"])))
res = cenv[filtr]["particles"].mean()

filtr.value_counts()

print(f"średnia liczba cząsteczek (jesień, 50cm, dla stanowisk 3 i 4): {res:.2f}")

# Zadanie 5. Filtrowanie danych

Wczytaj zestaw danych `data/environmental_metadata_clean.csv`.

1. Wybierz z zestawu tylko próbki pobrane na stanowiskach na północ od Łodzi.
2. Wybierz z zestawu tylko próbki pobrane wiosną i jesienią.

In [ ]:
data = pd.read_csv("data/environmental_metadata_clean.csv")

In [ ]:
lokal = data.groupby(["latitude", "longitude"]).size().reset_index(name= "l_prob")
print(lokal)

In [ ]:
uć= 51.75
pn_uć= data[data["latitude"] > uć]
num= len(pn_uć)
polnoc= data[data["latitude"] > uć]

pnl= polnoc.groupby("site")[["latitude", "longitude"]].value_counts()
print(f"próbki na północ od Łodzi: {pnl}")

In [ ]:
u = polnoc.groupby("site")[["latitude", "longitude","season"]].value_counts().reset_index(name= "l_probek")
print(u)

In [ ]:
pora= (data["season"].isin(["spring", "summer"]))
data[pora]

# Zadanie 6. Analiza porównawcza

Odnieś się do podzbiorów danych uzyskanych w poprzednim zadaniu i wykonaj poniższe polecenia:
1. Z podzbioru stanowisk z północnej Polski wyodrębnionych w poprzednim zadaniu oblicz średnią temperaturę o każdej zbadanej porze roku. Oblicz to samo dla pozostałych stanowisk. Odpowiedz czy średnia temperatura na północy Polski jest widocznie wyższa niż na południu.
2. Z podzbioru prób zebranych wiosną i jesienią wyodrębnionych w poprzednim zadaniu oblicz średnią temperaturę i średnią wilgotność dla każdego stanowiska. Wykonaj zestawienie tych wartości z danymi dla całego roku. Oblicz różnicę tych wartości i odpowiedz czy istnieje wyraźny trend dla temperatury i wilgotności w chłodniejszych porach roku w stosunku do całego roku.
3. Sprawdź czy istnieje różnica w liczbie cząsteczek w wodzie w próbach pobranych wiosną i jesienią w stosunku do prób pobranych latem. Zbadaj trend dla poszczególnych głębokości.

In [ ]:
n_uć= data[data["latitude"] > uć]
n_temp= n_uć.groupby(["season"])["temperature"].mean()

s_uć= data[data["latitude"] < uć]
s_temp= s_uć.groupby(["season"])["temperature"].mean()

comparison= pd.merge(n_temp, s_temp, on="season")
print(f"Porównanie średnich temperatur: {comparison}")

#na polnocy temp nizsze niz na poludniu

In [ ]:
mean_por= data[pora].groupby("site")[["temperature", "humidity"]].mean()
mean_year= cenv.groupby("site")[["temperature", "humidity"]].mean()
trend= mean_por - mean_year

print(f"różnica parametrów: {trend} ")

#nie można określić dokładnego trendu, poniewaz niektore pomiary zostaly wykonane podczas jednej pory roku

In [ ]:
part_sa = data[pora].groupby("depth")["particles"].mean()
part_sum = data[data["season"] == "summer"].groupby("depth")["particles"].mean()

part_tr = part_sa - part_sum
print(f"trend cząsteczek wg głębokości: {part_tr} ")